### ISSUE TITLE
b2 - f1.txt

### ISSUE THREAD

**Issue by bahram700** [bahram5570/First-repository#8]
Is it good or needs some modifications?

**Comment by bahram700** [comment]
Is it good or needs some modifications?
https://github.com/bahram5570/First-repository/blob/b2/f1.txt

**Comment by bahram5570** [comment]
Add one more item.

**Comment by bahram700** [comment]
Check it out
https://github.com/bahram5570/First-repository/blob/b2/f1.txt

**Comment by bahram5570** [comment]
Good. Merge it.
